FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    curl libssl1.1 \
    && rm -rf /var/lib/apt/lists/*
# copy artifacts 
COPY ./output /app/
COPY ./insider-preview/entrypoint.sh /app/entrypoint.sh

WORKDIR /app/
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT [ "/app/entrypoint.sh" ]
