# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binlog_testtable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='binlog_testtable.proto',
  package='baikaldb.pb',
  syntax='proto2',
  serialized_options=_b('\200\001\001'),
  serialized_pb=_b('\n\x16\x62inlog_testtable.proto\x12\x0b\x62\x61ikaldb.pb\":\n\x10\x62inlog_testtable\x12\n\n\x02id\x18\x01 \x01(\x12\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\tB\x03\x80\x01\x01')
)




_BINLOG_TESTTABLE = _descriptor.Descriptor(
  name='binlog_testtable',
  full_name='baikaldb.pb.binlog_testtable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='baikaldb.pb.binlog_testtable.id', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='baikaldb.pb.binlog_testtable.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='baikaldb.pb.binlog_testtable.addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['binlog_testtable'] = _BINLOG_TESTTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

binlog_testtable = _reflection.GeneratedProtocolMessageType('binlog_testtable', (_message.Message,), {
  'DESCRIPTOR' : _BINLOG_TESTTABLE,
  '__module__' : 'binlog_testtable_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.binlog_testtable)
  })
_sym_db.RegisterMessage(binlog_testtable)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
