# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binlog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='binlog.proto',
  package='baikaldb.pb',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x62inlog.proto\x12\x0b\x62\x61ikaldb.pb\"\xc0\x01\n\x06\x42inlog\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.baikaldb.pb.BinlogType\x12\x10\n\x08start_ts\x18\x02 \x01(\x03\x12\x11\n\tcommit_ts\x18\x03 \x01(\x03\x12\x14\n\x0cprewrite_key\x18\x04 \x01(\x0c\x12\x32\n\x0eprewrite_value\x18\x05 \x01(\x0b\x32\x1a.baikaldb.pb.PrewriteValue\x12\x11\n\tddl_query\x18\x06 \x01(\x0c\x12\r\n\x05stmts\x18\x07 \x01(\x0c\"V\n\rPrewriteValue\x12\x16\n\x0eschema_version\x18\x01 \x01(\x03\x12-\n\tmutations\x18\x02 \x03(\x0b\x32\x1a.baikaldb.pb.TableMutation\"\x8e\x01\n\rTableMutation\x12\x10\n\x08table_id\x18\x01 \x01(\x03\x12\x13\n\x0binsert_rows\x18\x02 \x03(\x0c\x12\x13\n\x0bupdate_rows\x18\x03 \x03(\x0c\x12\x14\n\x0c\x64\x65leted_rows\x18\x04 \x03(\x0c\x12+\n\x08sequence\x18\x05 \x03(\x0e\x32\x19.baikaldb.pb.MutationType*G\n\nBinlogType\x12\x0c\n\x08PREWRITE\x10\x00\x12\n\n\x06\x43OMMIT\x10\x01\x12\x0c\n\x08ROLLBACK\x10\x02\x12\x07\n\x03\x44\x44L\x10\x03\x12\x08\n\x04\x46\x41KE\x10\x04*2\n\x0cMutationType\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02')
)

_BINLOGTYPE = _descriptor.EnumDescriptor(
  name='BinlogType',
  full_name='baikaldb.pb.BinlogType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PREWRITE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMIT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLLBACK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DDL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAKE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=457,
  serialized_end=528,
)
_sym_db.RegisterEnumDescriptor(_BINLOGTYPE)

BinlogType = enum_type_wrapper.EnumTypeWrapper(_BINLOGTYPE)
_MUTATIONTYPE = _descriptor.EnumDescriptor(
  name='MutationType',
  full_name='baikaldb.pb.MutationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=530,
  serialized_end=580,
)
_sym_db.RegisterEnumDescriptor(_MUTATIONTYPE)

MutationType = enum_type_wrapper.EnumTypeWrapper(_MUTATIONTYPE)
PREWRITE = 0
COMMIT = 1
ROLLBACK = 2
DDL = 3
FAKE = 4
INSERT = 0
UPDATE = 1
DELETE = 2



_BINLOG = _descriptor.Descriptor(
  name='Binlog',
  full_name='baikaldb.pb.Binlog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='baikaldb.pb.Binlog.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_ts', full_name='baikaldb.pb.Binlog.start_ts', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commit_ts', full_name='baikaldb.pb.Binlog.commit_ts', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prewrite_key', full_name='baikaldb.pb.Binlog.prewrite_key', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prewrite_value', full_name='baikaldb.pb.Binlog.prewrite_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ddl_query', full_name='baikaldb.pb.Binlog.ddl_query', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stmts', full_name='baikaldb.pb.Binlog.stmts', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=222,
)


_PREWRITEVALUE = _descriptor.Descriptor(
  name='PrewriteValue',
  full_name='baikaldb.pb.PrewriteValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema_version', full_name='baikaldb.pb.PrewriteValue.schema_version', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mutations', full_name='baikaldb.pb.PrewriteValue.mutations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=310,
)


_TABLEMUTATION = _descriptor.Descriptor(
  name='TableMutation',
  full_name='baikaldb.pb.TableMutation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_id', full_name='baikaldb.pb.TableMutation.table_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insert_rows', full_name='baikaldb.pb.TableMutation.insert_rows', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_rows', full_name='baikaldb.pb.TableMutation.update_rows', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted_rows', full_name='baikaldb.pb.TableMutation.deleted_rows', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='baikaldb.pb.TableMutation.sequence', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=455,
)

_BINLOG.fields_by_name['type'].enum_type = _BINLOGTYPE
_BINLOG.fields_by_name['prewrite_value'].message_type = _PREWRITEVALUE
_PREWRITEVALUE.fields_by_name['mutations'].message_type = _TABLEMUTATION
_TABLEMUTATION.fields_by_name['sequence'].enum_type = _MUTATIONTYPE
DESCRIPTOR.message_types_by_name['Binlog'] = _BINLOG
DESCRIPTOR.message_types_by_name['PrewriteValue'] = _PREWRITEVALUE
DESCRIPTOR.message_types_by_name['TableMutation'] = _TABLEMUTATION
DESCRIPTOR.enum_types_by_name['BinlogType'] = _BINLOGTYPE
DESCRIPTOR.enum_types_by_name['MutationType'] = _MUTATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Binlog = _reflection.GeneratedProtocolMessageType('Binlog', (_message.Message,), {
  'DESCRIPTOR' : _BINLOG,
  '__module__' : 'binlog_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.Binlog)
  })
_sym_db.RegisterMessage(Binlog)

PrewriteValue = _reflection.GeneratedProtocolMessageType('PrewriteValue', (_message.Message,), {
  'DESCRIPTOR' : _PREWRITEVALUE,
  '__module__' : 'binlog_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.PrewriteValue)
  })
_sym_db.RegisterMessage(PrewriteValue)

TableMutation = _reflection.GeneratedProtocolMessageType('TableMutation', (_message.Message,), {
  'DESCRIPTOR' : _TABLEMUTATION,
  '__module__' : 'binlog_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.TableMutation)
  })
_sym_db.RegisterMessage(TableMutation)


# @@protoc_insertion_point(module_scope)
