#!/usr/bin/python
#-*- coding:utf8 -*-
import base64
from dynamicMessage import parseFromString

from google.protobuf import message as _message
from store.interface_pb2 import StoreReq
from store import interface_pb2
import binlog_testtable_pb2

record_list = ["CD0YAiABOe1h38P7zgJTkQEFAAAAAAkAANIBHAiBgODh9ZyIDBCBgICAgKACGIGA4OH1nIgMIAPaASUIABCBgODh9ZyIDCoYEhYIAxIQCAISBW5hbWUxGgVhZGRyMSgA","CD0YAiABOfMy811ANC7PkQEFAAAAAAkAANIBHAiBgOCTip2IDBCCgICAgKACGIGA4JOKnYgMIAPaASUIABCBgOCTip2IDCoYEhYIAxIQCAQSBW5hbWUyGgVhZGRyMSgA","CD0YAiABOa1bax5yPxtakQEFAAAAAAkAANIBHAiBgND2op2IDBCDgICAgKACGIGA0PainYgMIAPaATcIABCBgND2op2IDCoqEigIAyIQCAISBW5hbWUxGgVhZGRyMSIQCAQSBW5hbWUyGgVhZGRyMSgC","CD0YAiABOcfluy8ZIPilkQEFAAAAAAkAANIBHAiBgNDrtJ2IDBCEgICAgKACGIGA0Ou0nYgMIAPaASUIABCBgNDrtJ2IDCoYEhYIAxIQCAYSBW5hbWUxGgVhZGRyMigA","CD0YAiABOX0sZFfyvrKzkQEBAAAAAAoAANIBHAiBgJCp4J+NDBCBgICAgMACGIGAkKngn40MIAPaAU8IABCBgJCp4J+NDCpCEkAIAxISCAgSBm5hbWUxMRoGYWRkcjExEhIIChIGbmFtZTEyGgZhZGRyMTISEggMEgZuYW1lMTMaBmFkZHIxMygA","CD0YAiABOZWE/+TKjIEnkQEBAAAAAAoAANIBHAiBgKDMgaCNDBCCgICAgMACGIGAoMyBoI0MIAPaAY8BCAAQgYCgzIGgjQwqgQESfwgDEhMIBhIFbmFtZTEaCGFkZHIgMTExEhQIChIGbmFtZTEyGghhZGRyIDExMRIUCAwSBm5hbWUxMxoIYWRkciAxMTEiEAgGEgVuYW1lMRoFYWRkcjIiEggKEgZuYW1lMTIaBmFkZHIxMiISCAwSBm5hbWUxMxoGYWRkcjEzKAE=","CD0YAiABOYptTA5b/q0NkQEBAAAAAAoAANIBHAiBgLCuq6ONDBCDgICAgMACGIGAsK6ro40MIAPaAYkCCAAQgYCwrqujjQwq+wESRggDEhQIDhIHbmFtZTExMRoHYWRkcjExMRIUCBASB25hbWUxMTIaB2FkZHIxMTISFAgSEgduYW1lMTEzGgdhZGRyMTEzKAASYQgDEhcIBhIJbmFtZSB0ZXN0GghhZGRyIDExMRIXCAoSCW5hbWUgdGVzdBoIYWRkciAxMTEiEwgGEgVuYW1lMRoIYWRkciAxMTEiFAgKEgZuYW1lMTIaCGFkZHIgMTExKAESGggDIhQIDBIGbmFtZTEzGghhZGRyIDExMSgCEjIIAxIVCBQSCG5hbWUxMTExGgdhZGRyMTExEhUIFhIIbmFtZTExMTIaB2FkZHIxMTIoAA=="]
record_list = ["CEAYAyAB0gEJCOSA0OS7+ZEM2gEUCAQQ5IDQ5Lv5kQwY5IDQ5Lv5kQw="]
record_list = ["CD0YAyABOc/U/5rBkfk1kQEHAAAAAAcAANIBHAiBgLDB2/mRDBCCgICAgOABGIGAsMHb+ZEMIALaASUIABCBgLDB2/mRDCoYEhYIAhIQCAISBW5hbWUxGgVhZGRyMSgA"]
record_list =["CD0YAyABOct1DD+I+TFDkQERAAAAAAkAANIBHAiBgIDGlaySDBCCgICAgKACGIGAgMaVrJIMIALaASUIABCBgIDGlaySDCoYEhYIAhIQCAYSBW5hbWUxGgVhZGRyMSgA","CD0YAyABOWA/6zkcWwCykQERAAAAAAkAANIBHAiBgNDWoaySDBCDgICAgKACGIGA0NahrJIMIALaASUIABCBgNDWoaySDCoYEhYIAhIQCAQSBW5hbWUxGgVhZGRyMSgA","CD0YAyABOZ1hDlJV2q0BkQEIAAAAAAoAANIBHAiBgODpga2SDBCCgICAgMACGIGA4OmBrZIMIALaAUkIABCBgODpga2SDCo8EjoIAiIQCAISBW5hbWUxGgVhZGRyMSIQCAQSBW5hbWUxGgVhZGRyMSIQCAYSBW5hbWUxGgVhZGRyMSgC","CD0YAyABOX0Z4uWqQJPCkQEIAAAAAAoAANIBHAiBgOCbs62SDBCDgICAgMACGIGA4JuzrZIMIALaASUIABCBgOCbs62SDCoYEhYIAhIQCAISBW5hbWUxGgVhZGRyMSgA","CD0YAyABOVn5C60PZFtpkQEFAAAAAAsAANIBHAiBgNDoka6SDBCDgICAgOACGIGA0OiRrpIMIALaASUIABCBgNDoka6SDCoYEhYIAhIQCAYSBW5hbWUyGgVhZGRyMigA","CD0YAyABOQSmf9sW4GORkQEJAAAAAAsAANIBHAiBgNDN+66SDBCGgICAgOACGIGA0M37rpIMIALaATcIABCBgNDN+66SDCoqEigIAiIQCAISBW5hbWUxGgVhZGRyMSIQCAYSBW5hbWUyGgVhZGRyMigC","CD0YAyABOQ5wlP2kqx0WkQESAAAAAAwAANIBHAiBgKDOxLmSDBCMgICAgIADGIGAoM7EuZIMIALaASUIABCBgKDOxLmSDCoYEhYIAhIQCAQSBW5hbWUyGgVhZGRyMigA","CD0YAyABOX3qxyNz/ghEkQEBAAAAAA0AANIBHAiBgLCb3b6SDBCCgICAgKADGIGAsJvdvpIMIALaASUIABCBgLCb3b6SDCoYEhYIAhIQCAYSBW5hbWUyGgVhZGRyMigA","CD0YAyABOWZLgZ3w8AexkQEDAAAAAAUAANIBHAiBgPDN+bSqDBCFgICAgKABGIGA8M35tKoMIALaASUIABCBgPDN+bSqDCoYEhYIAhIQCAoSBW5hbWU1GgVhZGRyNSgA"]
#record_list = ["CEAYAyAB0gEJCOSAgLrJ9JEM2gEUCAQQ5ICAusn0kQwY5ICAusn0kQw="]



for record_str in record_list:
    rec = base64.b64decode(record_str)
    #print rec
    print "------------------------------" 
    msg = interface_pb2.StoreReq()
    msg.ParseFromString(rec)
    print msg
    for mutation in msg.binlog.prewrite_value.mutations:
	print "insert rows:"
	rows = mutation.insert_rows
	print mutation.sequence[0] == 0
        for row in rows:
	    print base64.b64encode(row)
    
    
	rows = mutation.deleted_rows
	print "deleted rows:"
    
        for row in rows:
            rowObj = binlog_testtable_pb2.binlog_testtable()
            rowObj.ParseFromString(row)
        
       	    print rowObj

	rows = mutation.update_rows
	print "update rows:"
    
        for row in rows:
            rowObj = binlog_testtable_pb2.binlog_testtable()
            rowObj.ParseFromString(row)
        
       	    print rowObj
