# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft.proto',
  package='baikaldb.pb',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nraft.proto\x12\x0b\x62\x61ikaldb.pb\x1a\x0c\x63ommon.proto\"\xb4\x01\n\x12RaftControlRequest\x12+\n\x07op_type\x18\x01 \x02(\x0e\x32\x1a.baikaldb.pb.RaftControlOp\x12\x11\n\tregion_id\x18\x02 \x01(\x03\x12\x12\n\nnew_leader\x18\x03 \x01(\t\x12\x11\n\told_peers\x18\x04 \x03(\t\x12\x11\n\tnew_peers\x18\x05 \x03(\t\x12\x15\n\relection_time\x18\x06 \x01(\x03\x12\r\n\x05\x66orce\x18\x07 \x01(\x08\"o\n\x13RaftControlResponse\x12\x11\n\tregion_id\x18\x01 \x02(\x03\x12%\n\x07\x65rrcode\x18\x02 \x02(\x0e\x32\x14.baikaldb.pb.ErrCode\x12\x0e\n\x06leader\x18\x03 \x01(\t\x12\x0e\n\x06\x65rrmsg\x18\x04 \x01(\t*u\n\rRaftControlOp\x12\x0b\n\x07SetPeer\x10\x01\x12\x0f\n\x0bTransLeader\x10\x02\x12\x0c\n\x08SnapShot\x10\x03\x12\r\n\tGetLeader\x10\x04\x12\x0c\n\x08ShutDown\x10\x05\x12\x08\n\x04Vote\x10\x06\x12\x11\n\rResetVoteTime\x10\x07')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_RAFTCONTROLOP = _descriptor.EnumDescriptor(
  name='RaftControlOp',
  full_name='baikaldb.pb.RaftControlOp',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SetPeer', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TransLeader', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SnapShot', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GetLeader', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ShutDown', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Vote', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ResetVoteTime', index=6, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=337,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_RAFTCONTROLOP)

RaftControlOp = enum_type_wrapper.EnumTypeWrapper(_RAFTCONTROLOP)
SetPeer = 1
TransLeader = 2
SnapShot = 3
GetLeader = 4
ShutDown = 5
Vote = 6
ResetVoteTime = 7



_RAFTCONTROLREQUEST = _descriptor.Descriptor(
  name='RaftControlRequest',
  full_name='baikaldb.pb.RaftControlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_type', full_name='baikaldb.pb.RaftControlRequest.op_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='baikaldb.pb.RaftControlRequest.region_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_leader', full_name='baikaldb.pb.RaftControlRequest.new_leader', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='old_peers', full_name='baikaldb.pb.RaftControlRequest.old_peers', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_peers', full_name='baikaldb.pb.RaftControlRequest.new_peers', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='election_time', full_name='baikaldb.pb.RaftControlRequest.election_time', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='baikaldb.pb.RaftControlRequest.force', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=222,
)


_RAFTCONTROLRESPONSE = _descriptor.Descriptor(
  name='RaftControlResponse',
  full_name='baikaldb.pb.RaftControlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region_id', full_name='baikaldb.pb.RaftControlResponse.region_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errcode', full_name='baikaldb.pb.RaftControlResponse.errcode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leader', full_name='baikaldb.pb.RaftControlResponse.leader', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='baikaldb.pb.RaftControlResponse.errmsg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=335,
)

_RAFTCONTROLREQUEST.fields_by_name['op_type'].enum_type = _RAFTCONTROLOP
_RAFTCONTROLRESPONSE.fields_by_name['errcode'].enum_type = common__pb2._ERRCODE
DESCRIPTOR.message_types_by_name['RaftControlRequest'] = _RAFTCONTROLREQUEST
DESCRIPTOR.message_types_by_name['RaftControlResponse'] = _RAFTCONTROLRESPONSE
DESCRIPTOR.enum_types_by_name['RaftControlOp'] = _RAFTCONTROLOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RaftControlRequest = _reflection.GeneratedProtocolMessageType('RaftControlRequest', (_message.Message,), {
  'DESCRIPTOR' : _RAFTCONTROLREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.RaftControlRequest)
  })
_sym_db.RegisterMessage(RaftControlRequest)

RaftControlResponse = _reflection.GeneratedProtocolMessageType('RaftControlResponse', (_message.Message,), {
  'DESCRIPTOR' : _RAFTCONTROLRESPONSE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.RaftControlResponse)
  })
_sym_db.RegisterMessage(RaftControlResponse)


# @@protoc_insertion_point(module_scope)
