# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='statistics.proto',
  package='baikaldb.pb',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10statistics.proto\x12\x0b\x62\x61ikaldb.pb\x1a\x0c\x63ommon.proto\"\x83\x01\n\nBucketInfo\x12\x14\n\x0c\x64istinct_cnt\x18\x01 \x02(\x05\x12\x13\n\x0b\x62ucket_size\x18\x02 \x02(\x05\x12%\n\x05start\x18\x03 \x02(\x0b\x32\x16.baikaldb.pb.ExprValue\x12#\n\x03\x65nd\x18\x04 \x02(\x0b\x32\x16.baikaldb.pb.ExprValue\"\xa9\x01\n\nColumnInfo\x12,\n\x08\x63ol_type\x18\x01 \x02(\x0e\x32\x1a.baikaldb.pb.PrimitiveType\x12\x10\n\x08\x66ield_id\x18\x02 \x02(\x05\x12\x14\n\x0c\x64istinct_cnt\x18\x03 \x02(\x05\x12\x16\n\x0enull_value_cnt\x18\x04 \x02(\x05\x12-\n\x0c\x62ucket_infos\x18\x05 \x03(\x0b\x32\x17.baikaldb.pb.BucketInfo\"c\n\tHistogram\x12\x13\n\x0bsample_rows\x18\x01 \x02(\x03\x12\x12\n\ntotal_rows\x18\x02 \x02(\x03\x12-\n\x0c\x63olumn_infos\x18\x03 \x03(\x0b\x32\x17.baikaldb.pb.ColumnInfo\";\n\x0c\x43MsketchItem\x12\r\n\x05\x64\x65pth\x18\x01 \x02(\x05\x12\r\n\x05width\x18\x02 \x02(\x05\x12\r\n\x05value\x18\x03 \x02(\x05\"N\n\x0e\x43MsketchColumn\x12\x10\n\x08\x66ield_id\x18\x01 \x02(\x05\x12*\n\x07\x63mitems\x18\x02 \x03(\x0b\x32\x19.baikaldb.pb.CMsketchItem\"X\n\x08\x43Msketch\x12\r\n\x05\x64\x65pth\x18\x01 \x02(\x05\x12\r\n\x05width\x18\x02 \x02(\x05\x12.\n\tcmcolumns\x18\x03 \x03(\x0b\x32\x1b.baikaldb.pb.CMsketchColumn\"\x83\x01\n\nStatistics\x12\x10\n\x08table_id\x18\x01 \x02(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12)\n\thistogram\x18\x03 \x02(\x0b\x32\x16.baikaldb.pb.Histogram\x12\'\n\x08\x63msketch\x18\x04 \x02(\x0b\x32\x15.baikaldb.pb.CMsketch')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_BUCKETINFO = _descriptor.Descriptor(
  name='BucketInfo',
  full_name='baikaldb.pb.BucketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distinct_cnt', full_name='baikaldb.pb.BucketInfo.distinct_cnt', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucket_size', full_name='baikaldb.pb.BucketInfo.bucket_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='baikaldb.pb.BucketInfo.start', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='baikaldb.pb.BucketInfo.end', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=179,
)


_COLUMNINFO = _descriptor.Descriptor(
  name='ColumnInfo',
  full_name='baikaldb.pb.ColumnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col_type', full_name='baikaldb.pb.ColumnInfo.col_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_id', full_name='baikaldb.pb.ColumnInfo.field_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distinct_cnt', full_name='baikaldb.pb.ColumnInfo.distinct_cnt', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='null_value_cnt', full_name='baikaldb.pb.ColumnInfo.null_value_cnt', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucket_infos', full_name='baikaldb.pb.ColumnInfo.bucket_infos', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=351,
)


_HISTOGRAM = _descriptor.Descriptor(
  name='Histogram',
  full_name='baikaldb.pb.Histogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_rows', full_name='baikaldb.pb.Histogram.sample_rows', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_rows', full_name='baikaldb.pb.Histogram.total_rows', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column_infos', full_name='baikaldb.pb.Histogram.column_infos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=452,
)


_CMSKETCHITEM = _descriptor.Descriptor(
  name='CMsketchItem',
  full_name='baikaldb.pb.CMsketchItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth', full_name='baikaldb.pb.CMsketchItem.depth', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='baikaldb.pb.CMsketchItem.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='baikaldb.pb.CMsketchItem.value', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=513,
)


_CMSKETCHCOLUMN = _descriptor.Descriptor(
  name='CMsketchColumn',
  full_name='baikaldb.pb.CMsketchColumn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_id', full_name='baikaldb.pb.CMsketchColumn.field_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmitems', full_name='baikaldb.pb.CMsketchColumn.cmitems', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=593,
)


_CMSKETCH = _descriptor.Descriptor(
  name='CMsketch',
  full_name='baikaldb.pb.CMsketch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth', full_name='baikaldb.pb.CMsketch.depth', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='baikaldb.pb.CMsketch.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmcolumns', full_name='baikaldb.pb.CMsketch.cmcolumns', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=683,
)


_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='baikaldb.pb.Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_id', full_name='baikaldb.pb.Statistics.table_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='baikaldb.pb.Statistics.version', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='histogram', full_name='baikaldb.pb.Statistics.histogram', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmsketch', full_name='baikaldb.pb.Statistics.cmsketch', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=817,
)

_BUCKETINFO.fields_by_name['start'].message_type = common__pb2._EXPRVALUE
_BUCKETINFO.fields_by_name['end'].message_type = common__pb2._EXPRVALUE
_COLUMNINFO.fields_by_name['col_type'].enum_type = common__pb2._PRIMITIVETYPE
_COLUMNINFO.fields_by_name['bucket_infos'].message_type = _BUCKETINFO
_HISTOGRAM.fields_by_name['column_infos'].message_type = _COLUMNINFO
_CMSKETCHCOLUMN.fields_by_name['cmitems'].message_type = _CMSKETCHITEM
_CMSKETCH.fields_by_name['cmcolumns'].message_type = _CMSKETCHCOLUMN
_STATISTICS.fields_by_name['histogram'].message_type = _HISTOGRAM
_STATISTICS.fields_by_name['cmsketch'].message_type = _CMSKETCH
DESCRIPTOR.message_types_by_name['BucketInfo'] = _BUCKETINFO
DESCRIPTOR.message_types_by_name['ColumnInfo'] = _COLUMNINFO
DESCRIPTOR.message_types_by_name['Histogram'] = _HISTOGRAM
DESCRIPTOR.message_types_by_name['CMsketchItem'] = _CMSKETCHITEM
DESCRIPTOR.message_types_by_name['CMsketchColumn'] = _CMSKETCHCOLUMN
DESCRIPTOR.message_types_by_name['CMsketch'] = _CMSKETCH
DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BucketInfo = _reflection.GeneratedProtocolMessageType('BucketInfo', (_message.Message,), {
  'DESCRIPTOR' : _BUCKETINFO,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.BucketInfo)
  })
_sym_db.RegisterMessage(BucketInfo)

ColumnInfo = _reflection.GeneratedProtocolMessageType('ColumnInfo', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNINFO,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.ColumnInfo)
  })
_sym_db.RegisterMessage(ColumnInfo)

Histogram = _reflection.GeneratedProtocolMessageType('Histogram', (_message.Message,), {
  'DESCRIPTOR' : _HISTOGRAM,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.Histogram)
  })
_sym_db.RegisterMessage(Histogram)

CMsketchItem = _reflection.GeneratedProtocolMessageType('CMsketchItem', (_message.Message,), {
  'DESCRIPTOR' : _CMSKETCHITEM,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.CMsketchItem)
  })
_sym_db.RegisterMessage(CMsketchItem)

CMsketchColumn = _reflection.GeneratedProtocolMessageType('CMsketchColumn', (_message.Message,), {
  'DESCRIPTOR' : _CMSKETCHCOLUMN,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.CMsketchColumn)
  })
_sym_db.RegisterMessage(CMsketchColumn)

CMsketch = _reflection.GeneratedProtocolMessageType('CMsketch', (_message.Message,), {
  'DESCRIPTOR' : _CMSKETCH,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.CMsketch)
  })
_sym_db.RegisterMessage(CMsketch)

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), {
  'DESCRIPTOR' : _STATISTICS,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:baikaldb.pb.Statistics)
  })
_sym_db.RegisterMessage(Statistics)


# @@protoc_insertion_point(module_scope)
