name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Build the Docker image
      run: docker build . --tag ghcr.io/${{ github.repository_owner }}/baikaldb:$GITHUB_SHA
    - name: Push the Docker Image
      run: docker push ghcr.io/${{ github.repository_owner }}/baikaldb:$GITHUB_SHA
